parameters:

  is_debug: false

  app_dir: 'app'
  config_dir: 'config'
  cache_dir: 'cache'

  container_cache_file: 'CachedContainer.php'
  router_cache_file: 'Router.php'

  routes:
    welcome:
      path: '/'
      call: 'controller.welcome'

services:

  ##################################################
  # Application
  ##################################################

  application:
    class: 'Maverick\Application'
    arguments:
      - '@router'
      - '@container'
      - '@error_handler'

  ##################################################
  # Console Application
  ##################################################  

  console_application:
    class: 'Symfony\Component\Console\Application'
    calls:
      - ['add', ['@maverick.console.command.build']]

  maverick.console.command.build:
    class: 'Maverick\Console\Command\BuildCommand'

  ##################################################
  # HTTP Request
  ##################################################

  server_request:
    class: 'Psr\Http\Message\ServerRequestInterface'
    factory: ['GuzzleHttp\Psr7\ServerRequest', 'fromGlobals']

  ##################################################
  # Error Handler
  ##################################################  

  error_handler:
    class: 'Maverick\Handler\Error\WhoopsErrorHandler'
    arguments:
      - '@whoops.run'

  ##################################################
  # Container
  ##################################################

  container:
    class: 'Maverick\Container\Adapter\SymfonyDIAdapter'
    arguments:
      - '@service_container'

  ##################################################
  # Router and Routes
  ##################################################

  router:
    class: 'Maverick\Http\Router\FastRouteRouter'
    arguments:
      - '@fast_route.dispatcher'
      - '@route_collection'

  route_collection:
    class: 'Maverick\Http\Router\Route\Collection\Collection'
    configurator: ['@maverick.router.route.collection.configurator', 'configure']

  maverick.router.route.collection.configurator:
    class: 'Maverick\Http\Router\Route\Collection\Configurator\Configurator'
    arguments:
      - '@maverick.router.route.collection.loader'

  maverick.router.route.collection.loader:
    class: 'Maverick\Http\Router\Route\Collection\Loader\ConfigLoader'
    arguments:
      - '%routes%'

  maverick.router.dispatcher.utility.collection_processor:
    class: 'Maverick\Http\Router\Dispatcher\Utility\CollectionProcessor'
    arguments:
      - '@route_collection'

  ##################################################
  # Controllers
  ##################################################

  controller.welcome:
    class: Maverick\Controller\RenderableController
    arguments:
      - '@maverick.view.welcome'

  ##################################################
  # Views
  ##################################################

  maverick.view.welcome:
    class: 'Maverick\View\WelcomeView'

  not_found_view:
    class: 'Maverick\View\NotFoundView'

  not_allowed_view:
    class: 'Maverick\View\NotAllowedView'

  fatal_error_view:
    class: 'Maverick\View\FatalErrorView'

  ##################################################
  # Error Handlers
  ##################################################

  maverick.handler.error.whoops.http_exception:
    class: 'Maverick\Handler\Error\Whoops\HttpExceptionHandler'

  maverick.handler.error.whoops.safe_render:
    class: 'Maverick\Handler\Error\Whoops\SafeRenderHandler'
    arguments:
      - '@fatal_error_view'
    calls:
      - ['addView', [404, '@not_found_view']]
      - ['addView', [405, '@not_allowed_view']]

  ##################################################
  # Whoops
  ##################################################

  whoops.run:
    class: 'Whoops\Run'
    calls:
      - ['pushHandler', ['@whoops.handler.pretty']]
      - ['pushHandler', ['@maverick.handler.error.whoops.http_exception']]

  whoops.handler.pretty:
    class: 'Whoops\Handler\PrettyPageHandler'

  ##################################################
  # Fast route
  ##################################################

  fast_route.cached_dispatcher:
    class: 'FastRoute\Dispatcher'
    factory: 'FastRoute\cachedDispatcher'
    arguments:
      - '@maverick.router.dispatcher.utility.collection_processor'
      - {cacheFile: '%root_dir%/%cache_dir%/%router_cache_file%'}

  fast_route.dispatcher:
    alias: 'fast_route.cached_dispatcher'
