services:
    maverick.stdclass:
        class: stdclass

    maverick.http.request:
        class: Maverick\Http\Request
        factory: ["Maverick\\Http\\Request", "createFromGlobals"]

    maverick.http.response:
        class: Maverick\Http\Response
        factory: ["Maverick\\Http\\Response", "create"]

    maverick.router.collection:
        class: Symfony\Component\Routing\RouteCollection

    maverick.router:
        class: Maverick\Router\Router
        arguments: ["@maverick.router.collection"]

    maverick.controller.not_found:
        class: Maverick\Controller\NotFoundController